export const storeProducts = [
    {
    id: 1,
    title: "Con chó nhỏ và giỏ hoa hồng",
    img: "img/TieuThuyet/i-1.png",
    price: 10000,
    company:"Nguyễn Nhật Ánh",
    info:"Một quyển sách lôi cuốn viết cho tất cả chúng ta: trẻ con và người lớn. Cuộc đời của 5 con chó nhỏ: Haili, Batô, Suku, Êmê và Pig được tái hiện như đời sống của mỗi con người: tình bạn, tình yêu, đam mê, lòng dũng cảm, sự sợ hãi, và những ước mơ...",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-x.png",
    rating5:"img/star-x.png",
    inCart: false,
    count: 0,
    total:0
},
{
    id:2,
    title: "Bồ câu không đưa thư",
    img: "img/TieuThuyet/i-2.jpg",
    price:47560,
    company:"Nguyễn Nhật Ánh",
    info:"Câu chuyện bắt đầu từ lá thư làm quen để trong học bàn của Thục, trong bộ ba Xuyến, Thục, Cúc Hương. Lá thư chân tình đã thu hút sự tò mò của bộ ba, và họ bị cuốn hút vào trò chơi với người giấu mặt, dần hồi kéo theo Phán củi, anh chàng xấu xí vụng về của lớp làm quân sư và giúp xướng họa thơ. Cuộc truy tìm dẫn mọi người đến nhiều hiểu lầm tai hại và cả những bất ngờ thú vị. Và điều bất ngờ cuối cùng đã được phát hiện quá muộn. Vì sao? Xin để cho bạn đọc tự khám phá.",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-x.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
},
{
    id:3,
    title: "Chuộc tội",
    img: "img/TieuThuyet/i-3.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
},
{
    id:4,
    title: "Tiệm sách sau cơn mưa",
    img: "img/TieuThuyet/i-4.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
},
{
    id:5,
    title: "Ngày xưa có một chuyện tình",
    img: "img/TieuThuyet/i-5.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
}
,{
    id:6,
    title: "Tàu tốc hành",
    img: "img/TieuThuyet/i-6.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
},
{
    id:7,
    title: "Nhà giả kim",
    img: "img/TieuThuyet/i-7.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
},
{
    id:8,
    title: "Thuyết tán tỉnh cậu",
    img: "img/TieuThuyet/i-8.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
}];

export const vanhocProduct = [
    {
    id:1,
    title: "Tình yêu là gì mà thế giới phải khóc",
    img: "img/VanHoc/i-1.jpg",
    price:66750,
    company:"Quỳnh Thy",
    info:"Đây là cuốn sách sẽ giúp bạn chữa lành những vết thương và giúp bạn sẽ luôn tin vào tình yêu và sống một cuộc đời rực rỡ dù bạn đã từng tổn thương đến nhường nào.",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-x.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
},
{
    id:2,
    title: "Chúng ta là những đứa trẻ cô đơn",
    img: "img/VanHoc/i-2.jpg",
    price:66000,
    company:"Dưa hấu hạt tim",
    info:"Bạn đã bao giờ trở về nhà sau một ngày làm việc dài, mệt mỏi, áp lực, nằm dài trên ghế với bộ đồ công sở, bật thật lớn một bản nhạc deep house, át hết tất cả những âm thanh xung quanh và tự huyễn hoặc với chính mình rằng “Mình sẽ ổn thôi”?",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0 
},
{
    id:3,
    title: "Tôi có câu chuyện, bạn có rượu không?",
    img:"img/VanHoc/i-3.jpg" ,
    price:96750,
    company:"Quan đông dã khách",
    info:"Mỗi một thời khắc trên thế gian này đều có một câu chuyện đang xảy ra. Có những câu chuyện bạn đã từng trải qua, cả những câu chuyện mà bạn chưa từng trải qua, thế nhưng bất kể là chuyện gì, cũng đều đáng giá để được ghi nhớ trong lòng của mỗi người.",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-x.png",
    rating5:"img/star-x.png",
    inCart:false,
    count:0,
    total:0
},{
    id:4,
    title: "Tony buoi sang",
    img: "img/VanHoc/i-4.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
},{
    id:5,
    title: "Tony buoi sang",
    img: "img/VanHoc/i-5.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
}, {
    id:6,
    title: "Tony buoi sang",
    img: "img/VanHoc/i-6.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
},{
    id:7,
    title: "Tony buoi sang",
    img:"img/VanHoc/i-7.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
},{
    id: 8,
    title: "Tony buoi sang",
    img: "img/VanHoc/i-8.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
}
];
export const kinangProduct = [
    {
        id: 1,
        title: "Tony buoi sang",
        img: "img/Tamli/i-1.jpg",
        price:20,
        company:"aas",
        info:"kkk",
        rating1:"img/star-x.png",
        rating2:"img/star-x.png",
        rating3:"img/star-x.png",
        rating4:"img/star-y.png",
        rating5:"img/star-y.png",
        inCart:false,
        count:0,
        total:0
    },
    
        {
            id: 2,
            title: "Tony buoi sang",
            img: "img/Tamli/i-2.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
    
        {
            id: 3,
            title: "Tony buoi sang",
            img: "img/Tamli/i-3.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
    
        {
            id: 4,
            title: "Tony buoi sang",
            img: "img/Tamli/i-4.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
        {
            id: 5,
            title: "Tony buoi sang",
            img: "img/Tamli/i-5.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
        {
            id: 6,
            title: "Tony buoi sang",
            img: "img/Tamli/i-6.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
        {
            id: 7,
            title: "Tony buoi sang",
            img: "img/Tamli/i-7.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
        {
            id: 8,
            title: "Tony buoi sang",
            img:"img/Tamli/i-8.jpg" ,
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        }
    
]
export const banchayProduct = [
    {
        id: 1,
        title: "Tony buoi sang",
        img: "img/BanChay/i-1.jpg",
        price:20,
        company:"aas",
        info:"kkk",
        rating1:"img/star-x.png",
        rating2:"img/star-x.png",
        rating3:"img/star-x.png",
        rating4:"img/star-y.png",
        rating5:"img/star-y.png",
        inCart:false,
        count:0,
        total:0
    },
    
        {
            id: 2,
            title: "Tony buoi sang",
            img: "img/BanChay/i-2.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
    
        {
            id: 3,
            title: "Tony buoi sang",
            img: "img/BanChay/i-3.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
    
        {
            id: 4,
            title: "Tony buoi sang",
            img: "img/BanChay/i-4.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
        {
            id: 5,
            title: "Tony buoi sang",
            img: "img/BanChay/i-5.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
        {
            id: 6,
            title: "Tony buoi sang",
            img: "img/BanChay/i-6.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
        {
            id: 7,
            title: "Tony buoi sang",
            img: "img/BanChay/i-7.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
        {
            id: 8,
            title: "Tony buoi sang",
            img:"img/BanChay/i-8.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        }
    
]
export const dungcuProduct = [
    {
        id: 1,
        title: "Tony buoi sang",
        img: "img/Dungcu/i-1.jpg",
        price:20,
        company:"aas",
        info:"kkk",
        rating1:"img/star-x.png",
        rating2:"img/star-x.png",
        rating3:"img/star-x.png",
        rating4:"img/star-y.png",
        rating5:"img/star-y.png",
        inCart:false,
        count:0,
        total:0
    },
    
        {
            id: 2,
            title: "Tony buoi sang",
            img: "img/Dungcu/i-2.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
    
        {
            id: 3,
            title: "Tony buoi sang",
            img:"img/Dungcu/i-3.jpg" ,
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
    
        {
            id: 4,
            title: "Tony buoi sang",
            img: "img/Dungcu/i-4.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
        {
            id: 5,
            title: "Tony buoi sang",
            img: "img/Dungcu/i-5.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
        {
            id: 6,
            title: "Tony buoi sang",
            img: "img/Dungcu/i-6.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
        {
            id: 7,
            title: "Tony buoi sang",
            img: "img/Dungcu/i-7.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
        {
            id: 8,
            title: "Tony buoi sang",
            img:"img/Dungcu/i-8.jpg" ,
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        }
    
]
export const thieunhiProduct = [
    {
        id: 1,
        title: "Tony buoi sang",
        img: "img/ThieuNhi/i-1.jpg",
        price:20,
        company:"aas",
        info:"kkk",
        rating1:"img/star-x.png",
        rating2:"img/star-x.png",
        rating3:"img/star-x.png",
        rating4:"img/star-y.png",
        rating5:"img/star-y.png",
        inCart:false,
        count:0,
        total:0
    },
    
        {
            id: 2,
            title: "Tony buoi sang",
            img: "img/ThieuNhi/i-2.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
    
        {
            id: 3,
            title: "Tony buoi sang",
            img: "img/ThieuNhi/i-3.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
    
        {
            id: 4,
            title: "Tony buoi sang",
            img: "img/ThieuNhi/i-4.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
        {
            id: 5,
            title: "Tony buoi sang",
            img: "img/ThieuNhi/i-5.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
        {
            id: 6,
            title: "Tony buoi sang",
            img: "img/ThieuNhi/i-6.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
        {
            id: 7,
            title: "Tony buoi sang",
            img: "img/ThieuNhi/i-7.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
        {
            id: 8,
            title: "Tony buoi sang",
            img:"img/ThieuNhi/i-8.jpg" ,
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        }
    
]
export const detailProduct = [{
    id: 1,
    title: "Con chó nhỏ và giỏ hoa hồng",
    img: "img/i-1.png",
    price: 10,
    company:"NXB Van Hoc",
    info:"moi nguoi nen doc",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart: false,
    count: 0,
    total:0
}]
;
export const userProfile = {
    d : 1,
    k :1
};
export const searchSP=[{
    id: 1,
    title: "Tony buoi sang",
    img: "img/ThieuNhi/i-1.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
},

    {
        id: 2,
        title: "Tony buoi sang",
        img: "img/ThieuNhi/i-2.jpg",
        price:20,
        company:"aas",
        info:"kkk",
        rating1:"img/star-x.png",
        rating2:"img/star-x.png",
        rating3:"img/star-x.png",
        rating4:"img/star-y.png",
        rating5:"img/star-y.png",
        inCart:false,
        count:0,
        total:0
    },

    {
        id: 3,
        title: "Tony buoi sang",
        img: "img/ThieuNhi/i-3.jpg",
        price:20,
        company:"aas",
        info:"kkk",
        rating1:"img/star-x.png",
        rating2:"img/star-x.png",
        rating3:"img/star-x.png",
        rating4:"img/star-y.png",
        rating5:"img/star-y.png",
        inCart:false,
        count:0,
        total:0
    },

    {
        id: 4,
        title: "Tony buoi sang",
        img: "img/ThieuNhi/i-4.jpg",
        price:20,
        company:"aas",
        info:"kkk",
        rating1:"img/star-x.png",
        rating2:"img/star-x.png",
        rating3:"img/star-x.png",
        rating4:"img/star-y.png",
        rating5:"img/star-y.png",
        inCart:false,
        count:0,
        total:0
    },
    {
        id: 5,
        title: "Tony buoi sang",
        img: "img/ThieuNhi/i-5.jpg",
        price:20,
        company:"aas",
        info:"kkk",
        rating1:"img/star-x.png",
        rating2:"img/star-x.png",
        rating3:"img/star-x.png",
        rating4:"img/star-y.png",
        rating5:"img/star-y.png",
        inCart:false,
        count:0,
        total:0
    },
    {
        id: 6,
        title: "Tony buoi sang",
        img: "img/ThieuNhi/i-6.jpg",
        price:20,
        company:"aas",
        info:"kkk",
        rating1:"img/star-x.png",
        rating2:"img/star-x.png",
        rating3:"img/star-x.png",
        rating4:"img/star-y.png",
        rating5:"img/star-y.png",
        inCart:false,
        count:0,
        total:0
    },
    {
        id: 7,
        title: "Tony buoi sang",
        img: "img/ThieuNhi/i-7.jpg",
        price:20,
        company:"aas",
        info:"kkk",
        rating1:"img/star-x.png",
        rating2:"img/star-x.png",
        rating3:"img/star-x.png",
        rating4:"img/star-y.png",
        rating5:"img/star-y.png",
        inCart:false,
        count:0,
        total:0
    },
    {
        id: 8,
        title: "Tony buoi sang",
        img:"img/ThieuNhi/i-8.jpg" ,
        price:20,
        company:"aas",
        info:"kkk",
        rating1:"img/star-x.png",
        rating2:"img/star-x.png",
        rating3:"img/star-x.png",
        rating4:"img/star-y.png",
        rating5:"img/star-y.png",
        inCart:false,
        count:0,
        total:0
    }

]
