export const storeProducts = [
    {
    id: 1,
    title: "Con chó nhỏ và giỏ hoa hồng",
    img: "img/i-1.png",
    price: 10,
    company:"NXB Van Hoc",
    info:"moi nguoi nen doc",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart: false,
    count: 0,
    total:0
},
{
    id:2,
    title: "Bồ câu không đưa thư",
    img: "img/i-2.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
},
{
    id:3,
    title: "Chuộc tội",
    img: "img/i-3.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
},
{
    id:4,
    title: "Tiệm sách sau cơn mưa",
    img: "img/i-4.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
},
{
    id:5,
    title: "Ngày xưa có một chuyện tình",
    img: "img/i-5.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
}
,{
    id:6,
    title: "Tàu tốc hành",
    img: "img/i-6.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
},
{
    id:7,
    title: "Nhà giả kim",
    img: "img/i-7.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
},
{
    id:8,
    title: "Thuyết tán tỉnh cậu",
    img: "img/i-8.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
}];

export const vanhocProduct = [
    {
    id:1,
    title: "Tony buoi sang",
    img: "img/img-11.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
},
{
    id:2,
    title: "Tony buoi sang",
    img: "img/img-11.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0 
},
{
    id:3,
    title: "Tony buoi sang",
    img: "img/img-11.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
},{
    id:4,
    title: "Tony buoi sang",
    img: "img/img-11.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
},{
    id:5,
    title: "Tony buoi sang",
    img: "img/img-11.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
}, {
    id:6,
    title: "Tony buoi sang",
    img: "img/img-11.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
},{
    id:7,
    title: "Tony buoi sang",
    img: "img/img-11.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
},{
    id: 8,
    title: "Tony buoi sang",
    img: "img/img-11.jpg",
    price:20,
    company:"aas",
    info:"kkk",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart:false,
    count:0,
    total:0
}
];
export const kinangProduct = [
    {
        id: 1,
        title: "Tony buoi sang",
        img: "img/img-12.jpg",
        price:20,
        company:"aas",
        info:"kkk",
        rating1:"img/star-x.png",
        rating2:"img/star-x.png",
        rating3:"img/star-x.png",
        rating4:"img/star-y.png",
        rating5:"img/star-y.png",
        inCart:false,
        count:0,
        total:0
    },
    
        {
            id: 2,
            title: "Tony buoi sang",
            img: "img/img-13.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
    
        {
            id: 3,
            title: "Tony buoi sang",
            img: "img/img-13.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
    
        {
            id: 4,
            title: "Tony buoi sang",
            img: "img/img-12.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
        {
            id: 5,
            title: "Tony buoi sang",
            img: "img/img-12.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
        {
            id: 6,
            title: "Tony buoi sang",
            img: "img/img-12.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
        {
            id: 7,
            title: "Tony buoi sang",
            img: "img/img-12.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        },
        {
            id: 8,
            title: "Tony buoi sang",
            img: "img/img-12.jpg",
            price:20,
            company:"aas",
            info:"kkk",
            rating1:"img/star-x.png",
            rating2:"img/star-x.png",
            rating3:"img/star-x.png",
            rating4:"img/star-y.png",
            rating5:"img/star-y.png",
            inCart:false,
            count:0,
            total:0
        }
    
]
export const detailProduct = {
    id: 1,
    title: "Con chó nhỏ và giỏ hoa hồng",
    img: "img/i-1.png",
    price: 10,
    company:"NXB Van Hoc",
    info:"moi nguoi nen doc",
    rating1:"img/star-x.png",
    rating2:"img/star-x.png",
    rating3:"img/star-x.png",
    rating4:"img/star-y.png",
    rating5:"img/star-y.png",
    inCart: false,
    count: 0,
    total:0
}
;
export const userProfile = {
    d : 1,
    k :1
}